# src/utils/email_sender.py
# ============================================
# COMPETITORINTEL - Email Sender
# ============================================
#
# PURPOSE: Send reports via email
# NOTE: Uses Gmail SMTP (free) or can be configured for other providers
# ============================================

import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional

from src.utils.logger import log


class EmailSender:
    """
    Send emails with report attachments.

    Uses Gmail SMTP by default. Configure via environment variables:
    - EMAIL_SENDER: Your email address
    - EMAIL_PASSWORD: Your app password (not your regular password)
    - EMAIL_SMTP: SMTP server (default: smtp.gmail.com)
    - EMAIL_PORT: SMTP port (default: 587)
    """

    def __init__(self):
        self.sender = os.getenv("EMAIL_SENDER")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.smtp_server = os.getenv("EMAIL_SMTP", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("EMAIL_PORT", 587))

        if not self.sender or not self.password:
            log.warning("Email credentials not configured. Email sending disabled.")
            self.enabled = False
        else:
            self.enabled = True
            log.info(f"Email sender configured: {self.sender}")

    def send_report(
        self,
        to_email: str,
        subject: str,
        body: str,
        attachments: List[str] = None,
        html_body: str = None,
    ) -> bool:
        """
        Send a report via email.

        Args:
            to_email: Recipient email address
            subject: Email subject
            body: Plain text body
            attachments: List of file paths to attach
            html_body: HTML version of the body (optional)

        Returns:
            True if successful
        """
        if not self.enabled:
            log.warning("Email sending disabled. Configure EMAIL_SENDER and EMAIL_PASSWORD.")
            return False

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.sender
            msg["To"] = to_email

            # Plain text version
            msg.attach(MIMEText(body, "plain"))

            # HTML version if provided
            if html_body:
                msg.attach(MIMEText(html_body, "html"))

            # Attach files
            if attachments:
                for filepath in attachments:
                    if os.path.exists(filepath):
                        with open(filepath, "rb") as f:
                            part = MIMEBase("application", "octet-stream")
                            part.set_payload(f.read())
                            encoders.encode_base64(part)
                            filename = os.path.basename(filepath)
                            part.add_header(
                                "Content-Disposition", f'attachment; filename="{filename}"'
                            )
                            msg.attach(part)

            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)

            log.info(f"✅ Email sent to {to_email}")
            return True

        except Exception as e:
            log.error(f"Failed to send email: {e}")
            return False


# Create singleton instance
email_sender = EmailSender()


def send_report_email(
    to_email: str,
    topic_name: str,
    report_content: str,
    report_paths: List[str] = None,
    html_content: str = None,
) -> bool:
    """
    Convenience function to send a report email.

    Args:
        to_email: Recipient email
        topic_name: Topic name (used in subject)
        report_content: Report content (markdown)
        report_paths: List of file paths to attach
        html_content: HTML version of the report

    Returns:
        True if successful
    """
    subject = f"📊 Research Report: {topic_name}"

    # Plain text body
    body = f"""
Research Report: {topic_name}
Generated by CompetitorIntel

The report has been attached to this email.

---
CompetitorIntel - AI-Powered Competitive Intelligence
"""

    return email_sender.send_report(
        to_email=to_email,
        subject=subject,
        body=body,
        attachments=report_paths,
        html_body=html_content,
    )
