# src/utils/email_sender.py
# ============================================
# COMPETITORINTEL - Email Sender (SendGrid with Attachments)
# ============================================

import os
import base64
from typing import List, Optional
from src.utils.logger import log

try:
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition

    HAS_SENDGRID = True
except ImportError:
    HAS_SENDGRID = False
    log.warning("SendGrid not installed. Email sending disabled.")


class EmailSender:
    """
    Send emails with report attachments using SendGrid API.
    """

    def __init__(self):
        self.enabled = False
        self.sender = os.getenv("EMAIL_SENDER")
        self.api_key = os.getenv("SENDGRID_API_KEY")

        if self.sender and self.api_key and HAS_SENDGRID:
            self.enabled = True
            log.info(f"Email sender configured: {self.sender}")
        else:
            log.warning("Email sender not configured. Set SENDGRID_API_KEY and EMAIL_SENDER")

    def send_report(
        self,
        to_email: str,
        subject: str,
        body: str,
        attachments: List[str] = None,
        html_body: str = None,
    ) -> bool:
        """
        Send a report via email using SendGrid with attachments.
        """
        if not self.enabled:
            log.warning("Email disabled. Configure SENDGRID_API_KEY and EMAIL_SENDER.")
            return False

        try:
            message = Mail(
                from_email=self.sender, to_emails=to_email, subject=subject, plain_text_content=body
            )
            if html_body:
                message.html_content = html_body

            # Add attachments if provided
            if attachments:
                for filepath in attachments:
                    if os.path.exists(filepath):
                        with open(filepath, "rb") as f:
                            data = f.read()
                            encoded = base64.b64encode(data).decode()

                            attachment = Attachment(
                                FileContent(encoded),
                                FileName(os.path.basename(filepath)),
                                FileType("application/octet-stream"),
                                Disposition("attachment"),
                            )
                            message.attachment = attachment
                            log.debug(f"Attached: {filepath}")

            sg = SendGridAPIClient(self.api_key)
            response = sg.send(message)

            if response.status_code == 202:
                log.info(f"✅ Email sent to {to_email}")
                return True
            else:
                log.error(f"Email failed with status: {response.status_code}")
                return False

        except Exception as e:
            log.error(f"Email error: {e}")
            return False


# Create singleton instance
email_sender = EmailSender()


def send_report_email(
    to_email: str,
    topic_name: str,
    report_content: str,
    report_paths: List[str] = None,
    html_content: str = None,
) -> bool:
    """
    Convenience function to send a report email.
    """
    subject = f"Research Report: {topic_name}"

    # Plain text body
    body = f"""
Research Report: {topic_name}
Generated by CompetitorIntel

The report has been attached to this email.

---
CompetitorIntel - AI-Powered Competitive Intelligence Analyst
"""

    return email_sender.send_report(
        to_email=to_email,
        subject=subject,
        body=body,
        attachments=report_paths,
        html_body=html_content,
    )
