# src/utils/report_formatter.py
# ============================================
# COMPETITORINTEL - Report Formatter
# ============================================
#
# PURPOSE: Format reports as HTML, PDF, and email
# ============================================

from datetime import datetime
from typing import List, Dict, Optional, Any

import markdown
from weasyprint import HTML

from src.utils.logger import log


def markdown_to_html(md_content: str) -> str:
    """
    Convert markdown to HTML.

    Args:
        md_content: Markdown content

    Returns:
        HTML string
    """
    return markdown.markdown(md_content, extensions=["extra", "tables", "fenced_code"])


def generate_html_report(report_content: str, title: str) -> str:
    """
    Generate a full HTML report with styling.

    Args:
        report_content: The report content (markdown)
        title: Report title

    Returns:
        Complete HTML page
    """
    html_body = markdown_to_html(report_content)

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
            color: #1a1a2e;
            background: #f8f9fa;
        }}
        .report-container {{
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1, h2, h3, h4, h5, h6 {{
            color: #2d3436;
            margin-top: 1.5em;
        }}
        h1 {{
            border-bottom: 3px solid #6c5ce7;
            padding-bottom: 10px;
        }}
        h2 {{
            border-bottom: 2px solid #dfe6e9;
            padding-bottom: 8px;
        }}
        a {{
            color: #6c5ce7;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 16px 0;
        }}
        th, td {{
            border: 1px solid #dfe6e9;
            padding: 10px 12px;
            text-align: left;
        }}
        th {{
            background: #f1f2f6;
            font-weight: 600;
        }}
        tr:nth-child(even) {{
            background: #f8f9fa;
        }}
        blockquote {{
            border-left: 4px solid #6c5ce7;
            margin: 16px 0;
            padding: 10px 20px;
            background: #f8f9fa;
        }}
        code {{
            background: #f1f2f6;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #dfe6e9;
            font-size: 0.85em;
            color: #636e72;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="report-container">
        {html_body}
        <div class="footer">
            Generated by CompetitorIntel &bull; {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
        </div>
    </div>
</body>
</html>"""


def save_pdf(html_content: str, output_path: str) -> bool:
    """
    Save HTML as PDF.

    Args:
        html_content: HTML string
        output_path: Path to save PDF

    Returns:
        True if successful
    """
    try:
        HTML(string=html_content).write_pdf(output_path)
        log.info(f"✅ PDF saved to {output_path}")
        return True
    except Exception as e:
        log.error(f"Failed to generate PDF: {e}")
        return False


def save_html(html_content: str, output_path: str) -> bool:
    """
    Save HTML to file.

    Args:
        html_content: HTML string
        output_path: Path to save HTML

    Returns:
        True if successful
    """
    try:
        with open(output_path, "w") as f:
            f.write(html_content)
        log.info(f"✅ HTML saved to {output_path}")
        return True
    except Exception as e:
        log.error(f"Failed to save HTML: {e}")
        return False

def is_report_meaningful(report_content: str) -> bool:
    """
    Check if a report is meaningful (not empty, not an error message).

    Args:
        report_content: The report content to check

    Returns:
        True if the report is meaningful
    """
    if not report_content or len(report_content.strip()) < 200:
        return False

    # Check for common "no data" messages
    no_data_patterns = [
        "no data available",
        "no content found",
        "no research data",
        "no information found",
        "unable to find",
        "no results found",
        "no memories found",
        "please run the researcher",
        "no additional content",
        "no findings",
    ]

    lower_content = report_content.lower()

    # If the report is mostly an error message, reject it
    for pattern in no_data_patterns:
        if pattern in lower_content:
            # Check if the pattern appears multiple times or is prominent
            if lower_content.count(pattern) > 1:
                return False

    # Check if it has proper structure (headings, sections)
    has_headings = any(mark in report_content for mark in ["#", "##", "###", "**"])

    # Check if it has substantial content
    has_substance = len(report_content.split()) > 150

    return has_headings and has_substance


def extract_report_from_results(results: List[Dict[str, Any]]) -> Optional[str]:
    """
    Extract a report from a list of results.

    Args:
        results: List of result dictionaries from agent context

    Returns:
        The report content or None
    """
    for r in reversed(results):
        if isinstance(r, dict):
            # Try different keys
            for key in ["report", "polished_report", "content", "response"]:
                content = r.get(key)
                if content and isinstance(content, str) and len(content) > 200:
                    # If it's a report, it should have structure
                    if "#" in content or "**" in content or len(content) > 500:
                        return content

    return None