# src/utils/email_sender.py
# ============================================
# COMPETITORINTEL - Email Sender (SendGrid)
# ============================================

import os
from typing import List, Optional
from src.utils.logger import log

# Try to import SendGrid, fallback if not available
try:
    from .email_sender_sendgrid import send_email_sendgrid

    HAS_SENDGRID = True
except ImportError:
    HAS_SENDGRID = False
    log.warning("SendGrid not available. Email sending disabled.")


class EmailSender:
    """
    Send emails with report attachments using SendGrid.
    """

    def __init__(self):
        self.enabled = False
        self.sender = os.getenv("EMAIL_SENDER")
        self.api_key = os.getenv("SENDGRID_API_KEY")

        if self.sender and self.api_key and HAS_SENDGRID:
            self.enabled = True
            log.info(f"Email sender configured: {self.sender}")
        else:
            log.warning("Email sender not configured. Set SENDGRID_API_KEY and EMAIL_SENDER")

    def send_report(
        self,
        to_email: str,
        subject: str,
        body: str,
        attachments: List[str] = None,
        html_body: str = None,
    ) -> bool:
        """
        Send a report via email.
        """
        if not self.enabled:
            log.warning("Email disabled. Configure SENDGRID_API_KEY and EMAIL_SENDER.")
            return False

        # Send using SendGrid
        return send_email_sendgrid(to_email, subject, body, html_body)


# Create singleton instance
email_sender = EmailSender()


def send_report_email(
    to_email: str,
    topic_name: str,
    report_content: str,
    report_paths: List[str] = None,
    html_content: str = None,
) -> bool:
    """
    Convenience function to send a report email.
    """
    subject = f"Research Report: {topic_name}"

    # Plain text body
    body = f"""
Research Report: {topic_name}
Generated by CompetitorIntel

The report has been attached to this email.

---
CompetitorIntel - AI-Powered Competitive Researcher 
"""

    return email_sender.send_report(
        to_email=to_email,
        subject=subject,
        body=body,
        attachments=report_paths,
        html_body=html_content,
    )
